blank_issues_enabled: true
contact_links:
  - name: ðŸ§± NHSE Technology Enhanced Learning (TEL) Design System
    url: https://technologyenhancedlearning.github.io/tel-frontend/
    about: "The TEL Design system is based off of the NHSE design system. View TEL patterns, components, and accessibility guidance."
