blank_issues_enabled: true
contact_links:
  - name: NHSE Technology Enhanced Learning (TEL) Design System
    url: https://technologyenhancedlearning.github.io/tel-frontend/
    about: The TEL Design system is based on the NHSE design system. View TEL patterns, components, and accessibility guidance.
